### PR TITLE
updated readme again

### LINKED ISSUE #5: AddMoreToReadMe
Add A HELLO

### PR DESCRIPTION
**Pull request by HraklisPapag**
This closes #6 
Notes:
uses object 1 to fix the error
@Ngewu @JoeSwaggott

### CODE REVIEW

**Comment by HraklisPapag** [comment]
Please correct spelling of something

**Comment by JoeSwaggott** [comment]
please say hello world @HraklisPapag

**Comment by HraklisPapag** [comment]
> please say hello world @HraklisPapag

Okay will do

**Comment by JoeSwaggott** [comment]
> 
sure thing

**Review by JoeSwaggott — COMMENTED** [review]
I liked the addition

**Review by HraklisPapag — COMMENTED** [review]
This was reviewed under commits

**Review by JoeSwaggott — CHANGES_REQUESTED** [review]
Requesting changes

**Review by Ngewu — CHANGES_REQUESTED** [review]
Please remove the last line

**Review by JoeSwaggott — APPROVED** [review]

**Review by Ngewu — APPROVED** [review]

**Pull request merged**
